[package]
name = "pindakaas"
version = "0.1.0"
authors = ["Jip J. Dekker <jip@dekker.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# num = "0.4" TODO: Coefficient
