[package]
name = "pindakaas-c"
version = "0.1.0"
authors = ["Jip J. Dekker <jip@dekker.one>"]
license = "MPL-2.0"

edition = "2021"

[lib]
name = "cpindakaas"
crate-type = ["staticlib"]  

[dependencies]
pindakaas = { path = "../pindakaas" }
libc = "0.2"

[build-dependencies]
cbindgen = "^0.20"
