[package]
name = "pindakaas"
description = "Encoding Integer and Pseudo Boolean constraints into CNF"
version = "0.1.0"
authors = [
	"Jip J. Dekker <jip.dekker@monash.edu>",
	"Hendrik 'Henk' Bierlee <hendrik.bierlee@monash.edu>",
]
license = "MPL-2.0"

edition = "2021"

[dependencies]
ipasir = { version = "0.3", features = ["ffi"] }
iset = "0.1.1"
itertools = "0.10"
num = "0.4"
rustc-hash = "1.1.0"

# Optional encoding tracing capabilities
tracing = { version = "0.1.37", optional = true }

# Optional Solver Interfaces
minisat = { git = "https://github.com/luteberget/minisat-rs.git", optional = true } # waiting on release for minisat::Lit::var()
splr = { version = "0.16", optional = true }

[dev-dependencies]
splr = { version = "0.16", features = ["incremental_solver"] }
test-log = { version = "0.2.11", features = ["trace"] }
env_logger = "0.9.3"
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
	"env-filter",
	"fmt",
] }

[features]
trace = ["tracing"]
default = ["trace"]
