[package]
name = "pindakaas"
description = "Encoding Integer and Pseudo Boolean constraints into CNF"
version = "0.1.0"
authors = [
	"Jip J. Dekker <jip.dekker@monash.edu>",
	"Hendrik 'Henk' Bierlee <hendrik.bierlee@monash.edu>"
]
license = "MPL-2.0"

edition = "2021"

[dependencies]
num = "^0.4"
itertools = "^0.10"

[dev-dependencies]
splr = { git = "ssh://git@github.com:22/shnarazk/splr.git", branch = "dev-0.16.3", features = ["incremental_solver"] }
