[package]
name = "pindakaas"
description = "Encoding Integer and Pseudo Boolean constraints into CNF"
version = "0.1.0"
authors = [
	"Jip J. Dekker <jip.dekker@monash.edu>",
	"Hendrik 'Henk' Bierlee <hendrik.bierlee@monash.edu>",
]
license = "MPL-2.0"

edition = "2021"

[dependencies]
cached = "0.46"
iset = "0.2"
itertools = "0.11"
rustc-hash = "1.1"

# Optional encoding tracing capabilities
tracing = { version = "0.1", optional = true }

# Optional library to dynamically load solver libraries (through IPASIR interfaces)
libloading = { version = "0.8", optional = true }

# Optional Solver Interfaces
splr = { version = "0.17", optional = true }

[dev-dependencies]
splr = { version = "0.17", features = ["incremental_solver"] }
traced_test = { path = "../traced_test" }

[features]
trace = ["tracing"]
default = []
